- name: 下载kubectl二进制
  copy: src={{ base_dir }}/bin/kubectl dest={{ bin_dir }}/kubectl mode=0755

- name: 下载admin证书
  copy: src={{ item }} dest={{ ca_dir }}/{{ item }}
  with_items:
  - admin.pem
  - admin-key.pem

# 创建kubectl kubeconfig 文件
- name: 设置集群参数
  shell: "{{ bin_dir }}/kubectl config set-cluster kubernetes \
	--certificate-authority={{ ca_dir }}/ca.pem \
	--embed-certs=true \
	--server={{ KUBE_APISERVER }}"
- name: 设置客户端认证参数
  shell: "{{ bin_dir }}/kubectl config set-credentials admin \
	--client-certificate={{ ca_dir }}/admin.pem \
	--embed-certs=true \
	--client-key={{ ca_dir }}/admin-key.pem"
- name: 设置上下文参数
  shell: "{{ bin_dir }}/kubectl config set-context kubernetes \
	--cluster=kubernetes --user=admin"
- name: 选择默认上下文
  shell: "{{ bin_dir }}/kubectl config use-context kubernetes"
